"""Laporan audit PDF (PRD-F-02, task 6f) — generator PDF murni tanpa dependency
eksternal (stack G1 locked). A4, Helvetica/Helvetica-Bold, teks di-sanitasi ke
cp1252 (emoji → marker ASCII, karakter non-Latin → '?', gaya scripts/pdf_gen.py).

Konten dibangun dari hasil SSE dokumenter: metadata sesi + aggregate (6b) +
verdict (6c) + findings + tiket CAPA auto (6e). Localized via Accept-Language
(F-22): kamus `id` kanonikal + `en` (dipenuhi bertahap di 6h); locale selain itu
fallback ke id (F3).
"""

from __future__ import annotations

import zlib
from datetime import date, datetime

PAGE_W, PAGE_H = 595.28, 841.89  # A4 pt
MARGIN = 50
LINE_STEP = 15

# emoji → marker ASCII (anti-pemotongan viewer, sama dgn scripts/pdf_gen.py)
EMOJI_MARKERS = [
    ("\u2705", "[OK]"), ("\u274c", "[NO]"), ("\u23f3", "[TODO]"),
    ("\U0001f6a7", "[WIP]"), ("\U0001f512", "[LOCKED]"), ("\u26a0", "[WARN]"),
    ("\U0001f534", "[CRIT]"), ("\U0001f7e0", "[MAJ]"), ("\U0001f7e1", "[MIN]"),
    ("\U0001f535", "[INFO]"), ("\U0001f3af", "[GOAL]"), ("\U0001f504", "[OPEN]"),
    ("\u2714", "[OK]"), ("\u27a1", "->"), ("\u2b50", "[STAR]"),
    ("\u2192", "->"), ("\u2014", "-"),
]

LABELS_ID = {
    "title": "EHOS \u2014 Laporan Audit Hotel",
    "session": "No. Sesi Audit",
    "hotel": "Hotel",
    "department": "Departemen",
    "period": "Periode Audit",
    "audit_type": "Tipe Audit",
    "auditor": "Auditor",
    "published": "Diterbitkan",
    "status": "Status",
    "verdict_header": "Hasil Audit",
    "total_score": "Skor Total",
    "verdict": "Keputusan",
    "pass": "PASS",
    "fail": "FAIL",
    "not_assessed": "Belum dinilai",
    "hazards": "Life-Safety Hazard",
    "hazard_warn": "HAZARD \u2014 item keselamatan jiwa GAGAL",
    "scored_items": "Item dinilai",
    "missing_items": "Item belum dinilai",
    "na_items": "Item N/A",
    "sections_header": "Rincian per Section",
    "section": "Section",
    "achieved": "Poin",
    "ratio": "Capaian",
    "items": "Items",
    "findings_header": "Temuan (Non-Compliance)",
    "findings_none": "Tidak ada temuan \u2014 semua item lulus.",
    "sev": "Severity",
    "life_safety": "Life-Safety",
    "yes": "YA",
    "no": "TIDAK",
    "capa_header": "Tiket CAPA Otomatis",
    "capa_note": "Sesuai PRD-F-03, temuan life-safety membentuk tiket CAPA Priority 1 (1x24 jam).",
    "capa_count": "Tiket dibuat",
    "items_header": "Rincian Per Item",
    "item_code": "Kode",
    "question": "Pertanyaan",
    "rubric": "Rubrik",
    "result": "Hasil",
    "res_pass": "PASS",
    "res_fail": "FAIL",
    "res_na": "N/A",
    "res_missing": "MISSING",
    "res_review": "REVIEW",
    "page": "Halaman",
    "footer_note": "Dokumen dihasilkan sistem EHOS \u2014 data kualitatif & kuatitatif dari PostgreSQL.",
}

LABELS_EN = {
    "title": "EHOS \u2014 Hotel Audit Report",
    "session": "Audit Session ID",
    "hotel": "Hotel",
    "department": "Department",
    "period": "Audit Period",
    "audit_type": "Audit Type",
    "auditor": "Auditor",
    "published": "Published",
    "status": "Status",
    "verdict_header": "Audit Result",
    "total_score": "Total Score",
    "verdict": "Verdict",
    "pass": "PASS",
    "fail": "FAIL",
    "not_assessed": "Not assessed",
    "hazards": "Life-Safety Hazards",
    "hazard_warn": "HAZARD \u2014 life-safety item FAILED",
    "scored_items": "Items scored",
    "missing_items": "Items missing",
    "na_items": "Items N/A",
    "sections_header": "Section Breakdown",
    "section": "Section",
    "achieved": "Points",
    "ratio": "Achieved",
    "items": "Items",
    "findings_header": "Findings (Non-Compliance)",
    "findings_none": "No findings \u2014 all items passed.",
    "sev": "Severity",
    "life_safety": "Life-Safety",
    "yes": "YES",
    "no": "NO",
    "capa_header": "Auto CAPA Tickets",
    "capa_note": "Per PRD-F-03, life-safety findings raise Priority 1 CAPA tickets (1x24h).",
    "capa_count": "Tickets created",
    "items_header": "Item Breakdown",
    "item_code": "Code",
    "question": "Question",
    "rubric": "Rubric",
    "result": "Result",
    "res_pass": "PASS",
    "res_fail": "FAIL",
    "res_na": "N/A",
    "res_missing": "MISSING",
    "res_review": "REVIEW",
    "page": "Page",
    "footer_note": "Generated by EHOS system \u2014 quantitative & qualitative data from PostgreSQL.",
}


def _safe(text: object | None) -> str:
    t = str(text if text is not None else "")
    for emoji, marker in EMOJI_MARKERS:
        t = t.replace(emoji, marker)
    return t.encode("cp1252", "replace").decode("cp1252")


def _esc(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _wrap(text: str, size: float, max_w: float) -> list[str]:
    lines: list[str] = []
    for raw in _safe(text).split("\n"):
        cur = ""
        for word in raw.split(" "):
            trial = f"{cur} {word}".strip()
            if len(trial) * 0.48 * size > max_w and cur:
                lines.append(cur)
                cur = word
            else:
                cur = trial
        lines.append(cur)
    return lines


def _fmt_ratio(value: float | None) -> str:
    if value is None:
        return "-"
    return f"{value * 100:.1f}%"


def _fmt_date(value: date | datetime | None) -> str:
    if value is None:
        return "-"
    if isinstance(value, datetime):
        return value.strftime("%d-%m-%Y %H:%M")
    return value.strftime("%d-%m-%Y")


class Canvas:
    """Pengatur konten per-halaman A4 + break otomatis + footer nomor halaman."""

    def __init__(self, doc_title: str, page_label: str = "Halaman"):
        self._ops: list[str] = []
        self._y = PAGE_H - MARGIN * 2
        self._page = 1
        self._pages: list[bytes] = []
        self._title = _safe(doc_title)
        self._page_label = _safe(page_label)

    # ── primitif PDF ──────────────────────────────────────────────────────
    def _stroke(self, width: int = 1):
        self._ops.append(f"{width} w 0.2 0.2 0.2 RG")

    def text(self, line: str, *, size: float = 10, x: float | None = None,
             bold: bool = False, color: str | None = None) -> None:
        font = "/F2" if bold else "/F1"
        x = MARGIN if x is None else x
        if color:
            self._ops.append(f"{color} rg")
        self._ops.append(
            f"BT {font} {size} Tf {x:.1f} {self._y:.1f} Td "
            f"({_esc(_safe(line))}) Tj ET"
        )
        if color:
            self._ops.append("0 g")

    def hline(self, x1: float | None = None, x2: float | None = None) -> None:
        self._stroke()
        y = self._y - 4
        self._ops.append(f"{x1 or MARGIN:.1f} {y:.1f} m {x2 or PAGE_W - MARGIN:.1f} {y:.1f} l S")

    def shade(self, gray: float, height: float) -> None:
        y = self._y - height + 2
        self._ops.append(f"{gray:.2f} g {MARGIN:.1f} {y:.1f} {PAGE_W - 2 * MARGIN:.1f} {height:.1f} re f")
        self._ops.append("0 g")

    def gap(self, height: float = LINE_STEP) -> None:
        self._y -= height

    @property
    def needs_page(self) -> bool:
        return self._y < MARGIN * 2 + 40

    def new_page(self) -> None:
        self._pages.append(self._flush())
        self._ops = [self._header()]
        self._y = PAGE_H - MARGIN * 2
        self._page += 1

    def _flush(self) -> bytes:
        body = "\n".join(self._ops).encode("cp1252")
        return b"q\n" + body + b"\nQ"

    # ── header/footer per halaman ─────────────────────────────────────────
    def _header(self) -> str:
        return (
            f"BT /F2 9 Tf {MARGIN} {PAGE_H - MARGIN + 14:.1f} Td "
            f"({_esc(self._title)}) Tj ET "
            f"0.2 0.2 0.2 RG {MARGIN} {PAGE_H - MARGIN + 6:.1f} m "
            f"{PAGE_W - MARGIN} {PAGE_H - MARGIN + 6:.1f} l S"
        )

    def footer(self) -> None:
        self._ops.append(
            f"BT /F1 8 Tf {MARGIN} {MARGIN - 24:.1f} Td "
            f"({_esc(f'{self._page_label} {self._page}')}) Tj ET"
        )

    def finalize(self) -> list[bytes]:
        self.footer()
        self._pages.append(self._flush())
        return self._pages


def _build_pdf(pages: list[bytes]) -> bytes:
    """Rakit dokumen PDF: catalog → halaman → stream (FlateDecode)."""
    objs: list[bytes | bytearray] = []
    objs.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    n = len(pages)
    kids = []
    stream_data: list[bytes] = []
    for i, content in enumerate(pages):
        comp = zlib.compress(content)
        stream_data.append(comp)
        kids.append(f"{3 + 2 * i} 0 R".encode())
    objs.append(f"<< /Type /Pages /Kids [{' '.join(k.decode() for k in kids)}] /Count {n} >>".encode())
    f1_obj, f2_obj = 3 + 2 * n, 4 + 2 * n
    for i, comp in enumerate(stream_data):
        page_obj = 3 + i * 2
        stream_obj = page_obj + 1
        objs.append(
            (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W:.2f} {PAGE_H:.2f}] "
                f"/Resources << /Font << /F1 {f1_obj} 0 R /F2 {f2_obj} 0 R >> >> "
                f"/Contents {stream_obj} 0 R >>"
            ).encode()
        )
        objs.append(
            b"<< /Length %d /Filter /FlateDecode >>\nstream\n%s\nendstream" % (len(comp), comp)
        )
    # font standar
    objs.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")
    objs.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>")

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, o in enumerate(objs, start=1):
        offsets.append(len(out))
        out.extend(f"{i} 0 obj\n".encode())
        out.extend(o)
        out.extend(b"\nendobj\n")
    xref_pos = len(out)
    out.extend(f"xref\n0 {len(objs) + 1}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode())
    out.extend(f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode())
    return bytes(out)


# ─── renderer ──────────────────────────────────────────────────────────────

def _labels(locale: str) -> dict[str, str]:
    if locale == "en":
        return {**LABELS_ID, **LABELS_EN}  # F3: en fallback ke id
    return LABELS_ID


def render_audit_report(data: dict, locale: str = "id") -> bytes:
    """Susun isi laporan dari data (metadata + agg 6b + verdict 6c + findings + capa)."""
    L = _labels(locale)
    sess = data["session"]
    score = data.get("score", {})
    hazards = data.get("hazards", [])
    sections = data.get("sections", [])
    findings = data.get("findings", [])
    capa = data.get("capa", {})

    cv = Canvas(L["title"], page_label=L["page"])
    cv._ops = [cv._header()]

    # header identitas
    cv.text(f"{L['hotel']}: {sess['hotel_name']}  [{sess['hotel_code']}]",
            bold=True, size=12)
    cv.gap(14)
    cv.text(f"{L['session']}: {sess['session_id']}", size=9)
    cv.text(f"{L['department']}: {sess['department']}   {L['audit_type']}: {sess['audit_type']}", size=9)
    cv.text(f"{L['period']}: {sess['date_start']} \u2192 {sess['date_end']}   "
            f"{L['auditor']}: {sess['auditor_name']}", size=9)
    cv.text(f"{L['published']}: {sess['published_at']}   {L['status']}: {sess['status']}", size=9)
    cv.hline()
    cv.gap(16)

    # blok verdict (shading)
    verdict_label = L["pass"] if score.get("pass_fail") == "PASS" else L["fail"]
    cv.shade(0.90, 52)
    cv.text(f"{L['verdict_header']}", bold=True, size=11)
    cv.gap(14)
    cv.text(f"{L['total_score']}: {score.get('total_score', '0')}%   {L['verdict']}: {verdict_label}",
            bold=True, size=11)
    cv.gap(3)
    cv.text(
        f"{L['scored_items']}: {score.get('items_scored', 0)}   "
        f"{L['missing_items']}: {score.get('items_missed', 0)}   "
        f"{L['na_items']}: {score.get('items_na', 0)}",
        size=8.5,
    )
    cv.gap(18)
    if hazards:
        cv.text(L["hazard_warn"], bold=True, size=10, color="1 0 0")
        for h in hazards:
            cv.text(f"  \u2022 {h['code']} \u2014 {h['question_text']}", size=8.5)
        cv.gap(12)

    # sections
    cv.text(L["sections_header"], bold=True, size=11)
    cv.hline()
    cv.gap(4)
    for s in sections:
        cv.text(
            f"{s['code']}  \u2014  {s['name']}",
            bold=True, size=9.5,
        )
        cv.gap(10)
        cv.text(f"   {L['ratio']}: {_fmt_ratio(s['ratio'])}   {L['achieved']}: "
                f"{s['achieved_points']:.1f}/{s['max_points']:.1f}   "
                f"{L['items']}: {s['items_scored']}",
                size=8.5)
        cv.gap(10)
        if cv.needs_page:
            cv.new_page()
    cv.hline()
    cv.gap(16)

    # findings + capa
    cv.text(L["findings_header"], bold=True, size=11)
    cv.hline()
    cv.gap(4)
    if not findings:
        cv.text(L["findings_none"], size=9)
    for f in findings:
        cv.text(f"{f['code']}  \u2014  {f['question_text']}", size=9)
        cv.text(
            f"   {L['sev']}: {f['severity']}   {L['life_safety']}: "
            f"{L['yes'] if f['is_life_safety'] else L['no']}",
            size=8.5,
        )
        cv.gap(12)
    if capa:
        cv.gap(4)
        cv.text(L["capa_header"], bold=True, size=11)
        cv.text(f"{L['capa_count']}: {capa.get('count', 0)}   "
                f"P1: {capa.get('p1_count', 0)}", size=9)
        cv.text(L["capa_note"], size=8)
        cv.gap(14)

    # per-item detail (multi halaman)
    cv.text(L["items_header"], bold=True, size=11)
    cv.hline()
    cv.gap(4)
    for it in data.get("items", []):
        if cv.needs_page:
            cv.new_page()
        res = L["res_pass"] if it["ratio"] == 1.0 else (
            L["res_na"] if it["is_na"] else L["res_missing"] if it["missing"] else L["res_fail"])
        cv.text(f"{it['code']}  \u2014  {it['question_text']}", size=8.5)
        cv.text(
            f"   {L['rubric']}: {it['rubric_type']}   {it['achieved']:.1f}/{it['max_score']:.1f} "
            f"   {L['result']}: {res}"
            f"{'   [LIFE-SAFETY]' if it['is_life_safety'] else ''}",
            size=8,
        )
        cv.gap(10)

    return _build_pdf(cv.finalize())