from app.db.session import Base
from app.models import (  # noqa: F401
    AuditItemScore,
    AuditLog,
    AuditMedia,
    AuditSession,
    BillingMilestone,
    Brand,
    CapaMedia,
    CapaStatusHistory,
    CapaTicket,
    ChecklistItem,
    ChecklistSection,
    ChecklistTemplate,
    Finding,
    GovernmentSbmRate,
    Hotel,
    HotelDepartment,
    Lead,
    LeadActivity,
    LeadReferral,
    LegacyIngestionBatch,
    LegacyScoreRow,
    LoginAudit,
    Notification,
    Permission,
    Province,
    Quotation,
    Region,
    RfpRequest,
    Role,
    RolesPermission,
    SyncConflictLog,
    Translation,
    User,
    UserHotelAssignment,
    UserRegionAssignment,
    UserRole,
    UserSession,
)

__all__ = ["Base"]