"""initial schema 37 tables hybrid identity

Revision ID: 561c3026e315
Revises: 
Create Date: 2026-09-10 10:15:10.933429
"""
from collections.abc import Sequence

from alembic import op
import geoalchemy2  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '561c3026e315'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('code', name=op.f('uq_brands_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_brands_uuid'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_permissions_uuid'))
    )
    op.create_table('provinces',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces')),
    sa.UniqueConstraint('code', name=op.f('uq_provinces_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_provinces_uuid'))
    )
    op.create_table('regions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('sales_region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_regions_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_regions_uuid'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_level', sa.SmallInteger(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_roles_uuid'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('preferred_locale', sa.String(length=10), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_users_deleted_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_users_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid'))
    )
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('uuid', name=op.f('uq_audit_logs_uuid'))
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_id', 'at'], unique=False)
    op.create_index('ix_audit_logs_at', 'audit_logs', ['at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id', 'at'], unique=False)
    op.create_table('checklist_templates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('brand_tier', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_checklist_templates_published_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_templates')),
    sa.UniqueConstraint('department', 'name', 'version', name=op.f('uq_checklist_templates_department')),
    sa.UniqueConstraint('uuid', name=op.f('uq_checklist_templates_uuid'))
    )
    op.create_table('government_sbm_rates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('package_type', sa.String(length=20), nullable=False),
    sa.Column('max_rate_per_pax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_government_sbm_rates_province_id_provinces')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_government_sbm_rates_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_sbm_rates')),
    sa.UniqueConstraint('province_id', 'package_type', 'fiscal_year', name=op.f('uq_government_sbm_rates_province_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_government_sbm_rates_uuid'))
    )
    op.create_index('ix_sbm_province_year', 'government_sbm_rates', ['province_id', 'fiscal_year'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('geofence_radius_meters', sa.Integer(), nullable=False),
    sa.Column('mice_facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gm_id', sa.BigInteger(), nullable=True),
    sa.Column('rom_id', sa.BigInteger(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('terminate_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_hotels_brand_id_brands')),
    sa.ForeignKeyConstraint(['gm_id'], ['users.id'], name=op.f('fk_hotels_gm_id_users')),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_hotels_province_id_provinces')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_hotels_region_id_regions')),
    sa.ForeignKeyConstraint(['rom_id'], ['users.id'], name=op.f('fk_hotels_rom_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotels')),
    sa.UniqueConstraint('code', name=op.f('uq_hotels_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_hotels_uuid'))
    )
    op.create_index('idx_hotels_geo', 'hotels', ['geo'], unique=False, postgresql_using='gist')
    op.create_index('ix_hotels_brand', 'hotels', ['brand_id'], unique=False)
    op.create_index('ix_hotels_mice_facilities', 'hotels', ['mice_facilities'], unique=False, postgresql_using='gin')
    op.create_index('ix_hotels_region', 'hotels', ['region_id'], unique=False)
    op.create_index('ix_hotels_status', 'hotels', ['status'], unique=False)
    op.create_table('legacy_ingestion_batches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('hotel_code', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('fail_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_by', sa.BigInteger(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name=op.f('fk_legacy_ingestion_batches_imported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_ingestion_batches')),
    sa.UniqueConstraint('uuid', name=op.f('uq_legacy_ingestion_batches_uuid'))
    )
    op.create_table('login_audits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_audits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_audits')),
    sa.UniqueConstraint('uuid', name=op.f('uq_login_audits_uuid'))
    )
    op.create_index('ix_login_audits_email_at', 'login_audits', ['email_attempted', 'at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('uuid', name=op.f('uq_notifications_uuid'))
    )
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('roles_permissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_roles_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_roles_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_roles_permissions_role_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_roles_permissions_uuid'))
    )
    op.create_table('translations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_translations_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_translations_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translations')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'field', 'locale', name=op.f('uq_translations_entity_type')),
    sa.UniqueConstraint('uuid', name=op.f('uq_translations_uuid'))
    )
    op.create_index('ix_translations_entity', 'translations', ['entity_type', 'entity_id'], unique=False)
    op.create_table('user_region_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_user_region_assignments_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_region_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_region_assignments')),
    sa.UniqueConstraint('user_id', 'region_id', name=op.f('uq_user_region_assignments_user_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_user_region_assignments_uuid'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_user_roles_uuid'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('uuid', name=op.f('uq_user_sessions_uuid'))
    )
    op.create_index('ix_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('audit_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('audit_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auditor_id', sa.BigInteger(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pass_fail', sa.String(length=10), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('department_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subcategory_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('legacy_source_year', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], name=op.f('fk_audit_sessions_auditor_id_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_audit_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_audit_sessions_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], name=op.f('fk_audit_sessions_template_id_checklist_templates')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_audit_sessions_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_sessions')),
    sa.UniqueConstraint('hotel_id', 'department', 'date_start', 'audit_type', name='uq_audit_hotel_dept_period_type', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('uuid', name=op.f('uq_audit_sessions_uuid'))
    )
    op.create_index('ix_audit_client_id', 'audit_sessions', ['client_id'], unique=False)
    op.create_index('ix_audit_department_date', 'audit_sessions', ['department', 'date_start'], unique=False)
    op.create_index('ix_audit_hotel_status', 'audit_sessions', ['hotel_id', 'status'], unique=False)
    op.create_table('checklist_sections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['checklist_sections.id'], name=op.f('fk_checklist_sections_parent_id_checklist_sections')),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], name=op.f('fk_checklist_sections_template_id_checklist_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_sections')),
    sa.UniqueConstraint('template_id', 'code', name=op.f('uq_checklist_sections_template_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_checklist_sections_uuid'))
    )
    op.create_table('hotel_departments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hod_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hod_user_id'], ['users.id'], name=op.f('fk_hotel_departments_hod_user_id_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_departments_hotel_id_hotels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_departments')),
    sa.UniqueConstraint('hotel_id', 'code', name=op.f('uq_hotel_departments_hotel_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_hotel_departments_uuid'))
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_no', sa.String(length=30), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('institution_type', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('pic_name', sa.String(length=255), nullable=True),
    sa.Column('pic_phone', sa.String(length=20), nullable=True),
    sa.Column('pic_email', sa.String(length=255), nullable=True),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_est', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_from_hotel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_leads_created_by_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_leads_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_leads_owner_id_users')),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_leads_province_id_provinces')),
    sa.ForeignKeyConstraint(['referred_from_hotel_id'], ['hotels.id'], name=op.f('fk_leads_referred_from_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_leads_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('lead_no', name=op.f('uq_leads_lead_no')),
    sa.UniqueConstraint('uuid', name=op.f('uq_leads_uuid'))
    )
    op.create_index('ix_leads_hotel_status', 'leads', ['hotel_id', 'status'], unique=False)
    op.create_index('ix_leads_owner_followup', 'leads', ['owner_id', 'next_followup_at'], unique=False)
    op.create_table('legacy_score_rows',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('main_category', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('sub_category_child', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_csv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['legacy_ingestion_batches.id'], name=op.f('fk_legacy_score_rows_batch_id_legacy_ingestion_batches')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_legacy_score_rows_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_score_rows')),
    sa.UniqueConstraint('uuid', name=op.f('uq_legacy_score_rows_uuid'))
    )
    op.create_index('ix_legacy_batch', 'legacy_score_rows', ['batch_id'], unique=False)
    op.create_index('ix_legacy_hotel_period', 'legacy_score_rows', ['hotel_id', 'period_date'], unique=False)
    op.create_table('rfp_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ref_no', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('pic_name', sa.String(length=255), nullable=True),
    sa.Column('pic_phone', sa.String(length=20), nullable=True),
    sa.Column('pic_email', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_hotel_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_hotel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_hotel_id'], ['hotels.id'], name=op.f('fk_rfp_requests_assigned_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['target_hotel_id'], ['hotels.id'], name=op.f('fk_rfp_requests_target_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfp_requests')),
    sa.UniqueConstraint('ref_no', name=op.f('uq_rfp_requests_ref_no')),
    sa.UniqueConstraint('uuid', name=op.f('uq_rfp_requests_uuid'))
    )
    op.create_table('user_hotel_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_user_hotel_assignments_deleted_by_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_user_hotel_assignments_hotel_id_hotels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_hotel_assignments_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_hotel_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_hotel_assignments')),
    sa.UniqueConstraint('user_id', 'hotel_id', 'role_id', name=op.f('uq_user_hotel_assignments_user_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_user_hotel_assignments_uuid'))
    )
    op.create_index('ix_uh_assignment_hotel', 'user_hotel_assignments', ['hotel_id'], unique=False)
    op.create_index('ix_uh_assignment_role', 'user_hotel_assignments', ['role_id'], unique=False)
    op.create_index('ix_uh_assignment_user', 'user_hotel_assignments', ['user_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('rubric_type', sa.String(length=20), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('na_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_life_safety', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['checklist_sections.id'], name=op.f('fk_checklist_items_section_id_checklist_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items')),
    sa.UniqueConstraint('section_id', 'code', name=op.f('uq_checklist_items_section_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_checklist_items_uuid'))
    )
    op.create_table('lead_activities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_lead_activities_actor_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_activities_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activities')),
    sa.UniqueConstraint('uuid', name=op.f('uq_lead_activities_uuid'))
    )
    op.create_index('ix_lead_activities_lead', 'lead_activities', ['lead_id'], unique=False)
    op.create_table('lead_referrals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('from_hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('to_hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_hotel_id'], ['hotels.id'], name=op.f('fk_lead_referrals_from_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_referrals_lead_id_leads')),
    sa.ForeignKeyConstraint(['to_hotel_id'], ['hotels.id'], name=op.f('fk_lead_referrals_to_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_referrals')),
    sa.UniqueConstraint('uuid', name=op.f('uq_lead_referrals_uuid'))
    )
    op.create_index('ix_lead_referrals_to_hotel', 'lead_referrals', ['to_hotel_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quotation_no', sa.String(length=30), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('package_type', sa.String(length=20), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=True),
    sa.Column('sbm_rate_id', sa.BigInteger(), nullable=True),
    sa.Column('sbm_rate_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sbm_fiscal_year', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_approval_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quotations_created_by_users')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_quotations_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_quotations_lead_id_leads')),
    sa.ForeignKeyConstraint(['sbm_rate_id'], ['government_sbm_rates.id'], name=op.f('fk_quotations_sbm_rate_id_government_sbm_rates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('quotation_no', name=op.f('uq_quotations_quotation_no')),
    sa.UniqueConstraint('uuid', name=op.f('uq_quotations_uuid'))
    )
    op.create_index('ix_quotation_hotel_event', 'quotations', ['hotel_id', 'event_date'], unique=False)
    op.create_index('ix_quotation_lead', 'quotations', ['lead_id'], unique=False)
    op.create_table('audit_item_scores',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('room_ref', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('scored_by', sa.BigInteger(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('fk_audit_item_scores_item_id_checklist_items')),
    sa.ForeignKeyConstraint(['scored_by'], ['users.id'], name=op.f('fk_audit_item_scores_scored_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['audit_sessions.id'], name=op.f('fk_audit_item_scores_session_id_audit_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_item_scores')),
    sa.UniqueConstraint('session_id', 'item_id', 'room_ref', name='uq_audit_item_session_item_room', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('uuid', name=op.f('uq_audit_item_scores_uuid'))
    )
    op.create_index('ix_audit_item_item', 'audit_item_scores', ['item_id'], unique=False)
    op.create_index('ix_audit_item_session', 'audit_item_scores', ['session_id'], unique=False)
    op.create_table('billing_milestones',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_type', sa.String(length=20), nullable=False),
    sa.Column('doc_no', sa.String(length=100), nullable=True),
    sa.Column('doc_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_billing_milestones_quotation_id_quotations')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_billing_milestones_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_milestones')),
    sa.UniqueConstraint('uuid', name=op.f('uq_billing_milestones_uuid'))
    )
    op.create_index('ix_billing_due_status', 'billing_milestones', ['due_date', 'status'], unique=False)
    op.create_index('ix_billing_quotation', 'billing_milestones', ['quotation_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_life_safety', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_findings_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('fk_findings_item_id_checklist_items')),
    sa.ForeignKeyConstraint(['session_id'], ['audit_sessions.id'], name=op.f('fk_findings_session_id_audit_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('uuid', name=op.f('uq_findings_uuid'))
    )
    op.create_index('ix_findings_hotel_safety', 'findings', ['hotel_id', 'is_life_safety'], unique=False)
    op.create_table('sync_conflict_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('room_ref', sa.String(length=50), nullable=True),
    sa.Column('winning_value', sa.String(length=50), nullable=True),
    sa.Column('losing_value', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('fk_sync_conflict_logs_item_id_checklist_items')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_sync_conflict_logs_resolved_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['audit_sessions.id'], name=op.f('fk_sync_conflict_logs_session_id_audit_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_conflict_logs')),
    sa.UniqueConstraint('uuid', name=op.f('uq_sync_conflict_logs_uuid'))
    )
    op.create_table('audit_media',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('source_camera', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_valid', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('watermark_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_audit_media_finding_id_findings')),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('fk_audit_media_item_id_checklist_items')),
    sa.ForeignKeyConstraint(['session_id'], ['audit_sessions.id'], name=op.f('fk_audit_media_session_id_audit_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_media')),
    sa.UniqueConstraint('uuid', name=op.f('uq_audit_media_uuid'))
    )
    op.create_index('ix_audit_media_finding', 'audit_media', ['finding_id'], unique=False)
    op.create_index('ix_audit_media_session', 'audit_media', ['session_id'], unique=False)
    op.create_index('ix_audit_media_uploadstatus', 'audit_media', ['upload_status'], unique=False)
    op.create_table('capa_tickets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.BigInteger(), nullable=True),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('reporter_id', sa.BigInteger(), nullable=True),
    sa.Column('receipt_id', sa.String(length=12), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_capa_tickets_assigned_to_users')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_capa_tickets_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_capa_tickets_created_by_users')),
    sa.ForeignKeyConstraint(['department_id'], ['hotel_departments.id'], name=op.f('fk_capa_tickets_department_id_hotel_departments')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_capa_tickets_finding_id_findings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_capa_tickets_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_capa_tickets_reporter_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_tickets')),
    sa.UniqueConstraint('receipt_id', name=op.f('uq_capa_tickets_receipt_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_capa_tickets_uuid'))
    )
    op.create_index('ix_capa_assigned', 'capa_tickets', ['assigned_to'], unique=False)
    op.create_index('ix_capa_hotel_priority', 'capa_tickets', ['hotel_id', 'priority'], unique=False)
    op.create_index('ix_capa_status_due', 'capa_tickets', ['status', 'due_at'], unique=False)
    op.create_table('capa_media',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('source_camera', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_valid', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('watermark_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['capa_tickets.id'], name=op.f('fk_capa_media_ticket_id_capa_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_media')),
    sa.UniqueConstraint('uuid', name=op.f('uq_capa_media_uuid'))
    )
    op.create_table('capa_status_histories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_capa_status_histories_actor_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['capa_tickets.id'], name=op.f('fk_capa_status_histories_ticket_id_capa_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_status_histories')),
    sa.UniqueConstraint('uuid', name=op.f('uq_capa_status_histories_uuid'))
    )
    op.create_index('ix_capa_status_history_ticket', 'capa_status_histories', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capa_status_history_ticket', table_name='capa_status_histories')
    op.drop_table('capa_status_histories')
    op.drop_table('capa_media')
    op.drop_index('ix_capa_status_due', table_name='capa_tickets')
    op.drop_index('ix_capa_hotel_priority', table_name='capa_tickets')
    op.drop_index('ix_capa_assigned', table_name='capa_tickets')
    op.drop_table('capa_tickets')
    op.drop_index('ix_audit_media_uploadstatus', table_name='audit_media')
    op.drop_index('ix_audit_media_session', table_name='audit_media')
    op.drop_index('ix_audit_media_finding', table_name='audit_media')
    op.drop_table('audit_media')
    op.drop_table('sync_conflict_logs')
    op.drop_index('ix_findings_hotel_safety', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_billing_quotation', table_name='billing_milestones')
    op.drop_index('ix_billing_due_status', table_name='billing_milestones')
    op.drop_table('billing_milestones')
    op.drop_index('ix_audit_item_session', table_name='audit_item_scores')
    op.drop_index('ix_audit_item_item', table_name='audit_item_scores')
    op.drop_table('audit_item_scores')
    op.drop_index('ix_quotation_lead', table_name='quotations')
    op.drop_index('ix_quotation_hotel_event', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_lead_referrals_to_hotel', table_name='lead_referrals')
    op.drop_table('lead_referrals')
    op.drop_index('ix_lead_activities_lead', table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_table('checklist_items')
    op.drop_index('ix_uh_assignment_user', table_name='user_hotel_assignments')
    op.drop_index('ix_uh_assignment_role', table_name='user_hotel_assignments')
    op.drop_index('ix_uh_assignment_hotel', table_name='user_hotel_assignments')
    op.drop_table('user_hotel_assignments')
    op.drop_table('rfp_requests')
    op.drop_index('ix_legacy_hotel_period', table_name='legacy_score_rows')
    op.drop_index('ix_legacy_batch', table_name='legacy_score_rows')
    op.drop_table('legacy_score_rows')
    op.drop_index('ix_leads_owner_followup', table_name='leads')
    op.drop_index('ix_leads_hotel_status', table_name='leads')
    op.drop_table('leads')
    op.drop_table('hotel_departments')
    op.drop_table('checklist_sections')
    op.drop_index('ix_audit_hotel_status', table_name='audit_sessions')
    op.drop_index('ix_audit_department_date', table_name='audit_sessions')
    op.drop_index('ix_audit_client_id', table_name='audit_sessions')
    op.drop_table('audit_sessions')
    op.drop_index('ix_user_sessions_user', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('user_region_assignments')
    op.drop_index('ix_translations_entity', table_name='translations')
    op.drop_table('translations')
    op.drop_table('roles_permissions')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_login_audits_email_at', table_name='login_audits')
    op.drop_table('login_audits')
    op.drop_table('legacy_ingestion_batches')
    op.drop_index('ix_hotels_status', table_name='hotels')
    op.drop_index('ix_hotels_region', table_name='hotels')
    op.drop_index('ix_hotels_mice_facilities', table_name='hotels', postgresql_using='gin')
    op.drop_index('ix_hotels_brand', table_name='hotels')
    op.drop_index('idx_hotels_geo', table_name='hotels', postgresql_using='gist')
    op.drop_table('hotels')
    op.drop_index('ix_sbm_province_year', table_name='government_sbm_rates')
    op.drop_table('government_sbm_rates')
    op.drop_table('checklist_templates')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('provinces')
    op.drop_table('permissions')
    op.drop_table('brands')
    # ### end Alembic commands ###