"""EHOS seed data — brand tiers, provinces, city→province, coordinate fallback (Constraint H1)."""

BRANDS: list[dict] = [
    {"code": "SBH", "name": "Swiss-Belhotel", "tier": "Upscale"},
    {"code": "GSB", "name": "Grand Swiss-Belhotel", "tier": "Luxury"},
    {"code": "SBO", "name": "Swiss-Belboutique", "tier": "Boutique"},
    {"code": "SBN", "name": "Swiss-Belinn", "tier": "Midscale"},
    {"code": "SBX", "name": "Swiss-Belexpress", "tier": "Budget"},
    {"code": "ZST", "name": "Zest", "tier": "Budget"},
    {"code": "SBC", "name": "Swiss-Belcourt", "tier": "Midscale"},
    {"code": "SBR", "name": "Swiss-Belresort", "tier": "Eco-Resort"},
    {"code": "SBRD", "name": "Swiss-Belresidence", "tier": "Upscale"},
]

BRAND_BY_SOURCE_LABEL: dict[str, str] = {
    "Swiss-Belhotel": "SBH",
    "Grand Swiss-Belhotel": "GSB",
    "Swiss-Belboutique": "SBO",
    "Swiss-Belinn": "SBN",
    "Hotel Ciputra": "SBN",
    "Swiss-Belexpress": "SBX",
    "Zest": "ZST",
    "Swiss-Belcourt": "SBC",
    "Swiss-Belresort": "SBR",
    "Swiss-Belvillas": "SBR",
    "MAUA": "SBR",
    "Swiss-Belresidence": "SBRD",
}

PROVINCES: list[dict] = [
    {"code": "31", "name": "DKI Jakarta"},
    {"code": "32", "name": "Jawa Barat"},
    {"code": "33", "name": "Jawa Tengah"},
    {"code": "34", "name": "DI Yogyakarta"},
    {"code": "35", "name": "Jawa Timur"},
    {"code": "36", "name": "Banten"},
    {"code": "51", "name": "Bali"},
    {"code": "52", "name": "Nusa Tenggara Barat"},
    {"code": "53", "name": "Nusa Tenggara Timur"},
    {"code": "12", "name": "Sumatera Utara"},
    {"code": "15", "name": "Jambi"},
    {"code": "18", "name": "Lampung"},
    {"code": "14", "name": "Riau"},
    {"code": "21", "name": "Kepulauan Riau"},
    {"code": "19", "name": "Kepulauan Bangka Belitung"},
    {"code": "64", "name": "Kalimantan Timur"},
    {"code": "65", "name": "Kalimantan Utara"},
    {"code": "63", "name": "Kalimantan Selatan"},
    {"code": "62", "name": "Kalimantan Tengah"},
    {"code": "61", "name": "Kalimantan Barat"},
    {"code": "73", "name": "Sulawesi Selatan"},
    {"code": "71", "name": "Sulawesi Utara"},
    {"code": "72", "name": "Sulawesi Tengah"},
    {"code": "74", "name": "Sulawesi Tenggara"},
    {"code": "81", "name": "Maluku"},
    {"code": "91", "name": "Papua"},
    {"code": "94", "name": "Papua Tengah"},
    {"code": "95", "name": "Papua Selatan"},
    {"code": "92", "name": "Papua Barat"},
    {"code": "93", "name": "Papua Barat Daya"},
]

CITY_PROVINCE: dict[str, str] = {
    "Jakarta": "31",
    "Thamrin": "31",
    "Cibubur": "31",
    "Bandung": "32",
    "Bogor": "32",
    "Majalengka": "32",
    "Karawang": "32",
    "Cibitung": "32",
    "Cikarang": "32",
    "Cirebon": "32",
    "Indramayu": "32",
    "Surakarta": "33",
    "Semarang": "33",
    "Brebes": "33",
    "Yogyakarta": "34",
    "Surabaya": "35",
    "Malang": "35",
    "Manyar": "35",
    "Tangerang": "36",
    "Cilegon": "36",
    "Cikande": "36",
    "Bali": "51",
    "Ubud": "51",
    "Kuta": "51",
    "Sanur": "51",
    "Penida Island": "51",
    "Lombok": "52",
    "Kupang": "53",
    "Tambolaka": "53",
    "Medan": "12",
    "Jambi": "15",
    "Lampung": "18",
    "Pekanbaru": "14",
    "Batam City": "21",
    "Bangka Belitung": "19",
    "Pangkal Pinang": "19",
    "Balikpapan": "64",
    "Samarinda City": "64",
    "Tarakan": "65",
    "Banjarmasin": "63",
    "Batulicin": "63",
    "Palangkaraya": "62",
    "Singkawang": "61",
    "Makassar": "73",
    "Manado": "71",
    "Palu City": "72",
    "Luwuk": "72",
    "Kendari": "74",
    "Ambon": "81",
    "Jayapura": "91",
    "Biak": "91",
    "Timika": "94",
    "Merauke": "95",
    "Manokwari": "92",
    "Sorong": "93",
}

REGION_CODE: dict[str, str] = {
    "Bali": "BALI",
    "Jakarta": "JAKARTA",
    "Batam": "BATAM",
    "Sumatera, Riau, Bangka & Belitung Islands": "SUMBAGBEL",
    "West Nusa Tenggara": "NTB",
    "Central Java": "JATENG",
    "West Java": "JABAR",
    "Kalimantan": "KALIMANTAN",
    "Papua": "PAPUA",
    "Banten": "BANTEN",
    "East Java": "JATIM",
    "East Nusa Tenggara": "NTT",
    "Maluku": "MALUKU",
    "Sulawesi": "SULAWESI",
}

COORDINATE_FALLBACK: dict[str, tuple[float, float]] = {
    "SBAY": (-7.3296, 112.7426),
    "SCTH": (-6.1919, 106.825),
    "SBKB": (1.1183, 104.0358),
}

HOTEL_STATUS_MAP: dict[str, str] = {
    "Active": "ACTIVE",
    "Inactive": "TERMINATED",
}

HOTEL_DEPARTMENTS: list[dict] = [
    {"code": "GM", "name": "General Manager"},
    {"code": "HOUSEKEEPING", "name": "Housekeeping"},
    {"code": "KITCHEN_FB", "name": "Kitchen & Food Beverage"},
    {"code": "SECURITY_RISK", "name": "Security & Risk Management"},
]
